import React, { useState, useEffect } from 'react';
import { generateDailyMealPlan } from '../services/geminiService';
import { DailyPlan, UserPreferences, Recipe } from '../types';
import { DIET_OPTIONS, CALORIE_OPTIONS } from '../constants';
import { RecipeCard } from './RecipeCard';
import { Loader2, Wand2, Share2, Check, ExternalLink, History, CalendarClock } from 'lucide-react';

const PREFS_STORAGE_KEY = 'nutriplan_user_prefs';
const HISTORY_STORAGE_KEY = 'nutriplan_meal_history';

interface Props {
  initialSharedRecipe?: Recipe | null;
}

interface MealPlanHistoryItem {
  id: string;
  timestamp: string;
  plan: DailyPlan;
}

export const MealPlanner: React.FC<Props> = ({ initialSharedRecipe }) => {
  const [loading, setLoading] = useState(false);
  const [plan, setPlan] = useState<DailyPlan | null>(null);
  const [history, setHistory] = useState<MealPlanHistoryItem[]>([]);
  
  // Initialize from local storage if available
  const [preferences, setPreferences] = useState<UserPreferences>(() => {
    try {
      const saved = localStorage.getItem(PREFS_STORAGE_KEY);
      if (saved) {
        return JSON.parse(saved);
      }
    } catch (e) {
      console.error("Failed to load preferences from storage", e);
    }
    // Default fallback
    return {
      diet: DIET_OPTIONS[0],
      calories: 2000,
      allergies: ''
    };
  });

  const [copiedPlan, setCopiedPlan] = useState(false);

  // Load history on mount
  useEffect(() => {
    try {
      const savedHistory = localStorage.getItem(HISTORY_STORAGE_KEY);
      if (savedHistory) {
        setHistory(JSON.parse(savedHistory));
      }
    } catch (e) {
      console.error("Failed to load history", e);
    }
  }, []);

  // Save preferences whenever they change
  useEffect(() => {
    localStorage.setItem(PREFS_STORAGE_KEY, JSON.stringify(preferences));
  }, [preferences]);

  const saveToHistory = (newPlan: DailyPlan) => {
    const newItem: MealPlanHistoryItem = {
      id: Date.now().toString(),
      timestamp: new Date().toISOString(),
      plan: newPlan
    };
    
    // Prepend new item and keep only last 7
    const updatedHistory = [newItem, ...history].slice(0, 7);
    setHistory(updatedHistory);
    localStorage.setItem(HISTORY_STORAGE_KEY, JSON.stringify(updatedHistory));
  };

  const handleGenerate = async () => {
    setLoading(true);
    setPlan(null);
    try {
      const result = await generateDailyMealPlan(
        preferences.diet,
        preferences.calories,
        preferences.allergies
      );
      setPlan(result);
      if (result) {
        saveToHistory(result);
      }
    } catch (e) {
      alert("Failed to generate plan. Please check your API key and try again.");
    } finally {
      setLoading(false);
    }
  };

  const handleSharePlan = async () => {
    if (!plan) return;

    const text = `🥗 My Daily Meal Plan (${plan.totalCalories} kcal)\n\n🍳 Breakfast: ${plan.breakfast.name}\n🥗 Lunch: ${plan.lunch.name}\n🍽️ Dinner: ${plan.dinner.name}\n🍎 Snack: ${plan.snack.name}\n\nGenerated by NutriPlan AI`;

    if (navigator.share) {
      try {
        await navigator.share({
          title: 'My Daily Meal Plan',
          text: text,
        });
      } catch (err) {
        // Share cancelled
      }
    } else {
      try {
        await navigator.clipboard.writeText(text);
        setCopiedPlan(true);
        setTimeout(() => setCopiedPlan(false), 2000);
      } catch (err) {
        console.error('Failed to copy', err);
      }
    }
  };

  const restorePlan = (item: MealPlanHistoryItem) => {
    setPlan(item.plan);
    // Scroll to top of plan result
    window.scrollTo({ top: 400, behavior: 'smooth' });
  };

  const formatDate = (isoString: string) => {
    const date = new Date(isoString);
    return new Intl.DateTimeFormat('en-US', { month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' }).format(date);
  };

  return (
    <div className="max-w-4xl mx-auto p-4 sm:p-6 pb-24">
      <div className="mb-8">
        <h2 className="text-3xl font-bold text-slate-900 mb-2 tracking-wide">AI Meal Planner</h2>
        <p className="text-lg text-slate-600 font-medium">Tell us your preferences, and we'll sketch out the perfect day.</p>
      </div>

      {initialSharedRecipe && !plan && (
        <div className="mb-12 animate-in fade-in slide-in-from-top-4 duration-500">
           <div className="flex items-center gap-2 mb-4">
               <span className="bg-indigo-100 text-indigo-700 px-4 py-1.5 rounded-lg border-2 border-slate-900 font-bold shadow-[2px_2px_0px_0px_rgba(15,23,42,1)] flex items-center gap-2 -rotate-1">
                  <ExternalLink size={18} />
                  Shared with you
               </span>
           </div>
           <RecipeCard type="Shared Recipe" recipe={initialSharedRecipe} />
           
           <div className="my-10 relative flex items-center justify-center">
             <div className="absolute inset-0 flex items-center" aria-hidden="true">
               <div className="w-full border-t-2 border-slate-300 border-dashed"></div>
             </div>
             <div className="relative bg-[#fdfbf7] px-4">
               <span className="text-slate-400 font-bold">Create your own plan below</span>
             </div>
           </div>
        </div>
      )}

      <div className="bg-white p-6 rounded-2xl border-2 border-slate-900 shadow-[6px_6px_0px_0px_rgba(15,23,42,1)] mb-10 relative overflow-hidden">
        {/* Decorative corner */}
        <div className="absolute top-0 right-0 w-16 h-16 bg-yellow-100 rounded-bl-full -mr-8 -mt-8 border-l-2 border-b-2 border-slate-900 z-0"></div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 relative z-10">
          <div>
            <label className="block text-lg font-bold text-slate-900 mb-2">Diet Type</label>
            <div className="relative">
              <select 
                value={preferences.diet}
                onChange={(e) => setPreferences({...preferences, diet: e.target.value})}
                className="w-full appearance-none rounded-xl border-2 border-slate-900 text-slate-900 focus:ring-0 focus:border-emerald-500 focus:shadow-[4px_4px_0px_0px_#10b981] p-3 bg-white font-medium text-lg transition-all cursor-pointer"
              >
                {DIET_OPTIONS.map(opt => <option key={opt} value={opt}>{opt}</option>)}
              </select>
              <div className="pointer-events-none absolute inset-y-0 right-0 flex items-center px-3 text-slate-900">
                <svg className="fill-current h-4 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M9.293 12.95l.707.707L15.657 8l-1.414-1.414L10 10.828 5.757 6.586 4.343 8z"/></svg>
              </div>
            </div>
          </div>
          
          <div>
            <label className="block text-lg font-bold text-slate-900 mb-2">Calories Target</label>
            <div className="relative">
              <select 
                value={preferences.calories}
                onChange={(e) => setPreferences({...preferences, calories: Number(e.target.value)})}
                className="w-full appearance-none rounded-xl border-2 border-slate-900 text-slate-900 focus:ring-0 focus:border-emerald-500 focus:shadow-[4px_4px_0px_0px_#10b981] p-3 bg-white font-medium text-lg transition-all cursor-pointer"
              >
                 {CALORIE_OPTIONS.map(opt => <option key={opt} value={opt}>{opt} kcal</option>)}
              </select>
               <div className="pointer-events-none absolute inset-y-0 right-0 flex items-center px-3 text-slate-900">
                <svg className="fill-current h-4 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M9.293 12.95l.707.707L15.657 8l-1.414-1.414L10 10.828 5.757 6.586 4.343 8z"/></svg>
              </div>
            </div>
          </div>

          <div>
            <label className="block text-lg font-bold text-slate-900 mb-2">Allergies / Avoid</label>
            <input 
              type="text" 
              placeholder="e.g. Peanuts, Gluten"
              value={preferences.allergies}
              onChange={(e) => setPreferences({...preferences, allergies: e.target.value})}
              className="w-full rounded-xl border-2 border-slate-900 text-slate-900 placeholder:text-slate-400 focus:ring-0 focus:border-emerald-500 focus:shadow-[4px_4px_0px_0px_#10b981] p-3 bg-white font-medium text-lg transition-all"
            />
          </div>
        </div>

        <div className="mt-8 flex justify-end relative z-10">
          <button
            onClick={handleGenerate}
            disabled={loading}
            className="flex items-center gap-2 bg-emerald-500 hover:bg-emerald-400 text-white text-lg font-bold py-3 px-8 rounded-xl border-2 border-slate-900 shadow-[4px_4px_0px_0px_rgba(15,23,42,1)] active:shadow-none active:translate-x-1 active:translate-y-1 transition-all disabled:opacity-50 disabled:cursor-not-allowed disabled:active:shadow-[4px_4px_0px_0px_rgba(15,23,42,1)] disabled:active:translate-x-0 disabled:active:translate-y-0"
          >
            {loading ? <Loader2 className="animate-spin" size={24} /> : <Wand2 size={24} />}
            GENERATE PLAN
          </button>
        </div>
      </div>

      {plan && (
        <div className="animate-in fade-in slide-in-from-bottom-4 duration-500 mb-12">
           <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center mb-6 gap-4">
              <div>
                <h3 className="text-2xl font-bold text-slate-900">Your Daily Sketch</h3>
                <div className="inline-block mt-1 bg-emerald-200 border-2 border-slate-900 text-slate-900 px-3 py-0.5 rounded-lg text-sm font-bold shadow-[2px_2px_0px_0px_rgba(15,23,42,1)] rotate-2">
                  Total: {plan.totalCalories} kcal
                </div>
              </div>
              
              <button 
                onClick={handleSharePlan}
                className="flex items-center gap-2 bg-blue-500 hover:bg-blue-400 text-white px-4 py-2 rounded-xl border-2 border-slate-900 shadow-[2px_2px_0px_0px_rgba(15,23,42,1)] active:shadow-none active:translate-x-1 active:translate-y-1 transition-all font-bold"
              >
                {copiedPlan ? <Check size={20} /> : <Share2 size={20} />}
                {copiedPlan ? "Copied!" : "Share Plan"}
              </button>
           </div>

           <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
              <RecipeCard type="Breakfast" recipe={plan.breakfast} />
              <RecipeCard type="Lunch" recipe={plan.lunch} />
              <RecipeCard type="Dinner" recipe={plan.dinner} />
              <RecipeCard type="Snack" recipe={plan.snack} />
           </div>
        </div>
      )}

      {/* History Section */}
      {history.length > 0 && (
        <div className="border-t-2 border-slate-900/10 pt-8 animate-in fade-in duration-500">
           <h3 className="text-2xl font-bold text-slate-900 mb-6 flex items-center gap-2">
             <div className="p-1.5 bg-yellow-100 rounded-lg border-2 border-slate-900 rotate-[-3deg]">
               <History size={20} className="text-slate-900" />
             </div>
             Past Sketches
           </h3>
           
           <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
             {history.map((item) => (
               <button 
                 key={item.id}
                 onClick={() => restorePlan(item)}
                 className="text-left bg-white p-4 rounded-xl border-2 border-slate-900 shadow-[2px_2px_0px_0px_rgba(15,23,42,0.1)] hover:shadow-[4px_4px_0px_0px_rgba(15,23,42,1)] hover:-translate-y-0.5 transition-all group"
               >
                 <div className="flex items-center gap-2 text-slate-400 text-sm font-bold mb-2">
                   <CalendarClock size={16} />
                   {formatDate(item.timestamp)}
                 </div>
                 <div className="font-bold text-slate-900 text-lg group-hover:text-emerald-600 transition-colors">
                   {item.plan.dietaryType} Plan
                 </div>
                 <div className="text-slate-500 font-medium">
                   {item.plan.totalCalories} calories
                 </div>
               </button>
             ))}
           </div>
        </div>
      )}
    </div>
  );
};
